version: 2
executorType: docker

containerInfo:
  - image: wnameless/oracle-xe-11g

stages:
  - build:
      workDir: ~/ruby-oci8
      environment:
        DATABASE_VERSION: 11.2.0.1
        ORACLE_SID: XE
        DATABASE_NAME: XE
        ORA_SDTZ: 'Europe/Helsinki'
        TZ: 'Europe/Helsinki'
      steps:
        - type: checkout
        - type: shell
          command: id -a
