version: 2
executorType: docker

containerInfo:
  - image: wnameless/oracle-xe-11g

stages:
  - build:
      workDir: ~/ruby-oci8
      environment:
        ORACLE_HOME: /u01/app/oracle/product/11.2.0/xe
        NLS_LANG: AMERICAN_AMERICA.AL32UTF8
        ORACLE_BASE: /u01/app/oracle
        LD_LIBRARY_PATH: $ORACLE_HOME/lib
        PATH: $PATH:$ORACLE_HOME/jdbc/lib
        DATABASE_VERSION: 11.2.0.2
        ORACLE_SID: XE
        DATABASE_NAME: XE
        ORA_SDTZ: 'Europe/Helsinki'
        TZ: 'Europe/Helsinki'
      steps:
        - type: shell
          pwd: /
          command: apt-get update && apt-get install -y git curl make
        - type: checkout
        - type: shell
          command: id -a
        - type: shell
          command: /usr/bin/curl -L https://get.rvm.io | /bin/bash -s stable
        - type: shell
          command: /bin/bash -l -c "rvm requirements && rvm install 2.4.0"
        - type: shell
          command: /bin/bash -l -c "gem install bundler --no-ri --no-rdoc"
        - type: shell
          command: |
            echo "$ORACLE_HOME"
            set -evxu
            "$ORACLE_HOME/bin/sqlplus" -L -S / AS SYSDBA <<SQL
            @@cisetup/create_ruby_user.sql
            SQL
            exit
        - type: shell
          command: make check
